name: Bug Report
description: Help improve Retainer by filing a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## System information

        If on Linux, make sure you have tested the Flatpak release of Retainer through Flathub before opening a bug report. If the bug is not present in the Flatpak open the report with the package maintainer.

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: |
        Where did you install Retainer from?
      options:
        - Flathub
        - Flathub Beta
        - Windows Store
    validations:
      required: true

  - type: input
    id: distro
    attributes:
      label: OS
      description: What distribution are you currently using?
      placeholder: Fedora 37, Ubuntu 22.04, Windows 10...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Bug information

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Also please explain what behavior was expected.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: Logs
      description: |
        If you can access the about page, you can also view logs by going to About > Troubleshooting > Debugging Information.
        On Windows you can find these logs by pressing `Windows Key + r` and entering `%LOCALAPPDATA%`, and then navigating to `retainerdevs.Retainer_8mcfc8dhbzctc\LocalState\retainer`.
        On Linux the logs are at `~/.var/app/io.github.retainerdevs.Retainer/data/retainer`.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
