name: Feature Request
description: Suggest an idea for improving Retainer
title: "[Request]: "
labels: ["enhancement"]

body:
  - type: textarea
    id: what-happened
    attributes:
      label: Tell us the problem or your need
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: your-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: To fix this, I would [...]
    validations:
      required: true

  - type: textarea
    id: other-solutions
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or reference about the feature request here.
    validations:
      required: false
