on:
  push:
    tags:
      - '*'

name: Release
jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          update: true
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version:
            7.x
      - name: Build
        run: |
          dotnet tool install --global wix --version 4.0.0
          windows/build_windows.ps1 -arches x86, x64 -msi -release
      - uses: actions/upload-artifact@v3
        with:
          name: Reminders Installer
          path: |
            out/x64/Release/en-us/Reminders Installer x64.msi
            out/x86/Release/en-us/Reminders Installer x86.msi
